# apiVersion: v1
# kind: Service
# metadata:
#   name: web-flask-svc
#   labels:
#     env: dev
# spec:
#   type: ClusterIP # default - internal traffic
#   ports:
#     - port: 3000 # service port
#       targetPort: 5000 # container port
#   selector:
#     app: web-flask # same label with web-flask deployment

# apiVersion: v1
# kind: Service
# metadata:
#   name: web-flask-svc
#   labels:
#     env: dev
# spec:
#   type: NodePort
#   ports:
#     - port: 3000
#       targetPort: 5000
#   selector:
#     app: web-flask

# apiVersion: v1
# kind: Service
# metadata:
#   name: web-flask-svc
#   labels:
#     env: dev
# spec:
#   type: NodePort
#   ports:
#     - nodePort: 30036
#       port: 3000
#       targetPort: 5000
#   selector:
#     app: web-flask

apiVersion: v1
kind: Service
metadata:
  name: web-flask-svc
  namespace: demo
  labels:
    env: dev
spec:
  type: NodePort
  ports:
    - nodePort: 30036
      port: 3000
      targetPort: 5000
  selector:
    app: web-flask
